ALTER TABLE hotels ADD COLUMN IF NOT EXISTS default_country VARCHAR(100);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS default_id_type VARCHAR(30);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS phone_country_code VARCHAR(5);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS invoice_prefix VARCHAR(20);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS check_in_time VARCHAR(5);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS check_out_time VARCHAR(5);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5,2);
