export const GENDER_OPTIONS = ["MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY"] as const;

export const COUNTRY_OPTIONS = [
  "Rwanda",
  "Uganda",
  "Kenya",
  "Tanzania",
  "Burundi",
  "South Sudan",
  "Democratic Republic of the Congo",
  "Ethiopia",
  "Nigeria",
  "Ghana",
  "South Africa",
  "Morocco",
  "Egypt",
  "India",
  "China",
  "Japan",
  "United Arab Emirates",
  "United Kingdom",
  "France",
  "Germany",
  "Belgium",
  "Netherlands",
  "Italy",
  "Spain",
  "Canada",
  "United States",
  "Brazil",
  "Australia",
] as const;
